* Discussion of the feedback
\label{sec:dis}
In this section the feedback will be discussed and suggestions of improvements of the math study program, will be presented. 
We will start with class specific feedback, then discuss general feedback and finally suggested changes of the undergraduate math program structure. 
Finally, the author will give some meta feedback about the round table.

** Class specific feedback
\label{subsec:spec}
\paragraph{Positive feedback} There was positive feedback and satisfaction about the following classes/modules:
1) Undergraduate seminar: Generally well taught and a nice opportunity to practice presentations of mathematical work. Still also interesting content wise, the class gave a opportunity to cover some basic mathematics knowledge otherwise not covered in the study program.
2) Analysis II: A good class and well taught, but it should receive more credits corresponding to the high but necessary workload
3) Complex Analysis
4) The applied core math module
5) Number Theory
6) Calculus on Manifolds

\paragraph{Negative feedback} There was negative feedback additionally to the classes mentioned below, that should be removed completely from the study program:
\subparagraph{Real Analysis} Currently taught too slowly, last year was too quick
\subparagraph{Introductory Topology} The second part was too fast and hand-waivy, additionally too much time was lost teaching background of smooth manifolds, as opposed to e.g. teaching covering spaces in more detail and slower. 
Also some students lacked the background in Manifolds and (to some degree) Algebra.
\subparagraph{Numerical methods} Here programming should be used to implement the methods taught, specifically in homework exercises. 
Currently, everything is done by hand this is very tideous, restricts the questions in homework and exam (in order to remain feasible) and puts too much emphasis on
the computations as opposed to conceptional understanding. 
\subparagraph{Differential equations} Currently the class is too unstructured.


** General feedback
\label{subsec:gen}
Furthermore, there were a number of general complaints and suggestions brought up:
1) There is an under-representation of females in the math department (faculty)
2) Some professors should be more careful, when commenting on student's origins
3) Grades are often published late
4) TAs are currently only given SA contracts and SAs/TAs generally receive not enough hours (less then they are spending)
5) Also TAs receive too little guidance
6) The communication from faculty should be improved in general
7) In particular, the module coordinators were hardly accessible this semester
8) There should be lecture notes or at least announced pre-readings for math classes
    

** Suggestions for changing the math study program
\label{subsec:sug}
The following changes have been suggested:
*** First year structure
\paragraph{Mathematical software lab} Should be probably removed altogether. Mathematica skills are not useful for students, which are often not using Mathematica afterwards anyway (licenses are very expensive). 
If skills in a programming language are needed for a different class, they should be taught on demand. 
\paragraph{Analysis I} Give 7.5 ects for it, this is more appropriate for the workload (which is absolutely necessary for the students to understand the basic concepts). 
\paragraph{Advanced linear algebra} There should be an additional advanced linear algebra class (similiar to the current introductory linear algebra in the third semester). 
This advanced linear algebra class could be a alternative to the other linear algebra classes and should be mandatory at least for math and physics students. 
This way, linear algebra classes could be treated similarly to calculus with its different levels already existing.
Then, also the class introductory linear algebra in third semester and foundations of linear algebra in the second semester would be redundant.
\paragraph{Advanced Linear algebra II} This class would continue Advanced Linear Algebra I in the second semester. 
This is also the way linear algebra is taught in most public german universities.
*** Second year structure
\paragraph{Elements of Probability} This class should not be part of the math study program, it aims at a different audience and the pace of the class is thus too slow for math students. 
\paragraph{Elements of stochastic processes} Instead this class (already including all the content from Elements of Probability) should receive 5 ects.
\paragraph{Introductory Algebra and Introductory Topology/Calculus on Manifolds} Currently Introductory Algebra is taught in fourth semester and Introductory Topology/Calculus on Manifolds (alternating) in third semester. 
Instead Introductory Algebra should be taught in thirs semester and Introductory Topology/Calculus on Manifolds should be taught in fourth semester. 
\paragraph{Triangle classes} There should be more math triangle classes.
*** Third year
\paragraph{Project and Thesis} Students generally don't receive enough information about thesis work. 
In particular, deadlines and expectations are not communicated well and depend too much on the supervisor. 
\paragraph{World track} There should be more and better options for World track, the existing options should be better advertised.
\paragraph{Campus track} There are not enough math classes, so Campus track students are forced to take a non-math core module. 
It would be nice if students were allowed to take more specialization or graduate classes instead of a fourth core module, when choosing Campus track


*** Discussion
Here the main points are removing the math software lab and giving more credits to Analysis I, replacing Foundations of -- and Introductory Linear Algebra, by two 5 ects advanced linear algebra classes throughout the first year and to remove Elements of Probability and instead give 5 ects to Elements of Stochastic Processes, having two class slots per week, instead of just one.  
Also, the order in which students take algebra and Topology/Calculus on Manifolds should be changed.
Overall, these changes amount to one additional class of 5 ects to be taught (the second linear algebra class) and
furthermore move 5 major-related ects from second to the first year, however the overall amount of major-related credits remains the same. 
These changes are needed however, in order to ensure that math students learn prerequisites, before taking classes requiring them and could also be useful to students in other majors. 
Particularly, offering the proposed additional class "Advanced Linear Algebra I" following the same idea that lead to establishing different difficulty/abstraction levels for the calculus classes, can be useful at least also for physics students.
This is also the way linear algebra is taught at most German universities.
Finally, these changes would help better matching the credits received for classes to the actual workload and to better balance the math education across different areas of mathematics. 


** Meta observations
\label{subsec:meta}
In this subsection the round table will be discussed as a method of gathering feedback from students.
Overall, the round table was successful. Although only a minority of math students attended the round table, 
there were at least two students in each year as well as further students from other majors (mostly physics), taking the math classes. 
The feedback was very extensive, however still somewhat detailed discussion were possible. 
In particular, compared to the author's experience in the round table last year, 
there were both more and more constructive feedback as well as more student participating in the round table (partially due to the fact that now also first year students were invited).
Also, it proved to be useful to invite not only math students and to invite first year students. 
Therefore, the author wants to suggest these student organized round-tables as a useful addition to currently used ways of gathering feedback.
