* Discussion of the feedback
\label{sec:dis}
In this section the feedback will be discussed and suggestions of improvements of the math study program, will be presented. 
We will start with class specific feedback, then discuss general feedback and finally suggested changes of the undergraduate math program structure. 
Finally, the author will give some meta feedback about the round table.

** Class specific feedback
There was positive feedback for the following classes/modules:
1) Undergraduate seminar
2) Analysis II, but this should receive more credits
3) Complex Analysis
4) The applied core math module
5) Number Theory
6) Calculus on Manifolds

and negative feedback for (except for the classes already mentioned, that should be dropped):
1) Real Analysis, taught too slowly
2) Introductory Topology, second part was too fast and hand-waivy, additionally too much time was lost teaching background on smoth manifolds
3) Numerical methods, should cover programming to implement the methods, specifically in homework exercises
4) Differential equations, too unstructured

** General feedback
Furthermore, there were a number of general complaints and suggestions brought up:
1) There are not enough math classes, campus track students are forced to take a non-math core module
2) It would be nice if students were allowed to take several specialization or graduate classes instead of a fourth core module, when choosing campustrack
3) There is an under-representation of females in the math department (faculty)
4) Some professors should be more careful, when commenting on some students origins
5) Grades are often published late
6) TAs are currently only given SA contracts and SAs/TAs generally receive not enough hours (less then they are spending)
7) Also TAs receive too little guidance
8) Students receive not enough information about thesis work
9) Deadlines and expectations are not communicated well and depend on the supervisor
10) There should be more and better options for World track, the existing options should be better advertised
11) The communication from faculty should be improved in general
    1) In particular, the module coordinators were hardly accessible this semester
12) There should be lecture notes for math classes

** Suggestions for changing the math study program
The following changes have been suggested:
1) First year structure
   1) Remove the math software lab
   2) give 7.5ects for Analysis I
   3) Add an advanced linear algebra class (like the current introductory linear algebra in third semester)
   4) This, advanced linear algebra class could be treated similarly to calculus with its different levels already existing
   5) Additionally, add a class linear algebra II in second semester to continue the class advanced linear algebra in first semester
   6) Then, the classes foundations of linear algebra (3rd semester) and introductory linear algebra (4th semester) are redundant
2) Second year structure
   1) Give elements of stochastic processes 5ects
   2) Move introductory algebra to the third semester and Topology (or Calculus on Manifolds, this alternates) to the fourth
3) Triangle classes:
   1) There should be more math triangle classes

** Meta observations
In this subsection the round table will be discussed as a method of gathering feedback from students.
Overall, the round table was successful. Although only a minority of math students attended the round table, 
there were at least two students in each year as well as further students from other majors (mostly physics), taking the math classes. 
The feedback was very extensive, however still somewhat detailed discussion were possible. 
In particular, compared to the author's experience in the round table last year, 
there were both more and more constructive feedback as well as more student participating in the round table (partially due to the fact that now also first year students were invited).
Also, it proved to be useful to invite not only math students and to invite first year students. 
All in all, the author would propose these student organized round-tables as a useful addition to current ways of gathering feedback.


